### ISSUE TITLE
trying to upload ticket for a game

### ISSUE THREAD

**Issue by d3athrow** [TomEke/WiiU-Title-Key#11]
tik2sd's keys.txt gives me a .tik file that gives an error ```Is this a disk ticket?``` and the one .tik file in the folder that it does take never actually shows up for the game on the website nor does it show up in the RSS feed that it uploaded.

**Comment by TomEke** [comment]
keys.txt is currently not supported, see #9 . If a ticket doesn't show up, it could be one that is not available on the eshop

**Comment by d3athrow** [comment]
Well the ticket i'm trying to upload is for a game i purchased from the eshop, unless i'm misunderstanding you.

**Comment by TomEke** [comment]
eShop tickets will not be public because you have your unique ID in them
