### ISSUE TITLE
Some titles seem to be region-free, but are shown as JPN

### ISSUE THREAD

**Issue by naendow** [TomEke/WiiU-Title-Key#12]
Hey :)

Some titles on the database are shown as JPN (YouTube i.e.) but are installed on unmodified eu consoles as well. That is probably a prove that this titles are region-free.

Could you add region free to the database please?

**Comment by TomEke** [comment]
There is a ALL region which does not seem to be working correctly.

**Comment by TomEke** [comment]
YouTube is the only one is the database is that ALL region. 

Thanks for finding this!
