### ISSUE TITLE
export to json

### ISSUE THREAD

**Issue by d0t1q** [TomEke/WiiU-Title-Key#16]
Can we get json support for the site?

**Comment by sanelkukic** [comment]
It would be nice if we could get a API of sorts (preferably a JSON API) to be able to GET a game from the database. That is, if said API doesn't exist already.

**Comment by TomEke** [comment]
There is already a json listing at /json of the page. Is there anything else you require in it?

**Comment by d0t1q** [comment]
Nope! I don't know why I didnt bother looking there in the first place. 
Thanks
