### ISSUE TITLE
bad ticket

### ISSUE THREAD

**Issue by piratesephiroth** [TomEke/WiiU-Title-Key#2]
I guess the site does not validate the ticket signature.
I spotted 1 bad ticket: Pokémon Rumble U  - USA

(it doesn't matter much because it's an eshop exclusive, anyway)

**Comment by TomEke** [comment]
Hello thanks for the report.

I do validate signatures, but the console ID check was broken. Someone uploaded a ticket that wasn't from a disc and it had their console ID in it.
