### ISSUE TITLE
Issues with json on https://wiiu.titlekeys.com/json

### ISSUE THREAD

**Issue by Krutonium** [TomEke/WiiU-Title-Key#20]
So I am trying to parse it, and I have run into a couple of issues:

If a game is listed more than once, the JSON will return the game the correct number of times, but will not change the TitleID, TitleKey, Region, etc.

(For example, I have 6 identical copies of New Super Mario Bros U, which should be all 3 regions, with a patch for each.)

It would also be handy if it could supply the Type field, IE Patch vs eShop vs System Application vs Unknown as well as perhaps a download link for the ticket itself?

**Comment by TomEke** [comment]
I believe you are parsing the JSON incorrectly. I do not see multiple duplicate fields. 

The Type fields is based on the title ID. Please implement it on your side of the program. There is a ticket boolean if the title has a ticket. Tickets links is based on the title ID.

**Comment by Krutonium** [comment]
I'm an idiot. I just realized why it was broken the way it is >.<

How can I determine the type based on the titleID?

**Comment by TomEke** [comment]
http://wiiubrew.org/wiki/Title_database#Title-ID_Types
