### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by DanTheMan827** [TomEke/WiiU-Title-Key#21]
The domain doesn't seem to resolve to anything.

**Comment by TomEke** [comment]
Issue with the domain registrar. https://github.com/llakssz/CIAngel/issues/126#issuecomment-300297350

**Comment by silentguy256** [comment]
What kind of issue? Anything we can help you with? Kind of sad this happened just when I was getting around to get my 3ds to run homebrew...

**Comment by TomEke** [comment]
Problem with the domain registar, can't do anything if they do not respond.

There is a temporary (?) domain which should be up and running
