### ISSUE TITLE
Can't upload keys.txt or tickets after the new domain change.

### ISSUE THREAD

**Issue by nl255** [TomEke/WiiU-Title-Key#22]
I have been trying to upload my keys.txt to the Wii U title key site for a while but all I get is a "Whoops, looks like something went wrong." error.  The same applies when I try to upload a ticket.

**Comment by TomEke** [comment]
Please try again now.

**Comment by nl255** [comment]
It is still not working. Note that there are a few keys that are 0x2b8 or 0x350.  It is also possible that the latest version of tik2sd uses a different end of line format (such as dos/windows format instead of un*x format or whatever) and/or that it doesn't like the extra empty line at the end.

**Comment by TomEke** [comment]
I think I have found the problem in my server configuration. Please try again now.

**Comment by nl255** [comment]
It works fine now, thanks.
