### ISSUE TITLE
Feature to automatically encrypt title keys?

### ISSUE THREAD

**Issue by nl255** [TomEke/WiiU-Title-Key#23]
Now that it is trivial to dump the bootroms it would be nice if new title keys would be automatically encrypted (by reading the keys from boot9.rom) rather than it having to be done manually.

**Comment by DrakiaXYZ** [comment]
Really simple C program that will allow encrypting title keys purely on PC:
https://gist.github.com/TheDgtl/e36f97d924b80329eff6b54f52734684

It will require the keyslot 0x3D normal key, which can be found online now (Just search for "3ds AES keys", there's a Google Doc, you want the Common Key eShop normal key, starts with 64).
Proof: http://i.imgur.com/se5NGL1.png

I've cut out half of each of the keys just so this doesn't get flagged.

Generating the normal key yourself is kind of a pain, as it requires data from both the NATIVE_FIRM and bootrom, which is why I just made this program take in the normal key as a parm.

**Comment by TomEke** [comment]
This has already been implemented

https://github.com/TomEke/WiiU-Title-Key/blob/master/app/Title.php#L17

**Comment by DrakiaXYZ** [comment]
Ah, my code/references were actually in regards to the 3DS titlekeys, not the WiiU ones, but this is the only place I could reach you 👍 
With the new bootrom dump, it's now possible to do all the encryption entirely on the PC, no more having to manually copy things around and run stuff on the 3DS

**Comment by TomEke** [comment]
It is exactly the same on the 3DS side and has been implemented.

I left the comment in my usual HTML comment about it.

**Comment by DrakiaXYZ** [comment]
Oh weird, cause I know the other week there was a gap of a few days where keys were sitting in a decrypted-only state. 

I'm not seeing that function called anywhere, is it not actually hooked up yet? Or is it something not done automatically on submission?

**Comment by TomEke** [comment]
The other week, bootrom wasn't dumped yet.

It is done automatically when submitted on the backend.

**Comment by DrakiaXYZ** [comment]
Ah okay. 

Looking at that function, it actually looks to be doing a decrypt instead of encrypt?
Function to support encrypting, if you want to auto encrypt on submit of decrypted keys:
https://gist.github.com/TheDgtl/01575bea2e1e53aa00e9690613c3c16c

Stupid comments stripping code formatting

**Comment by TomEke** [comment]
Yes. On the WiiU site I only store encrypted keys. The 3DS version is different and stores both and will generate a encrypted key when a decrypted key is set. I will begin work on removing decrypted keys on the 3DS page soon.

**Comment by TomEke** [comment]
Also your implementation would not work as there are two different 0x3D keys

**Comment by DrakiaXYZ** [comment]
Hmm, according to the spreadsheet I found there's 6 normal keys for 0x3D. eShop, System, and 4 unknown. 

Shouldn't everything coming from the eShop be using the same one though?

**Comment by TomEke** [comment]
The database includes system titles from the CDN, not just eShop titles.

**Comment by DrakiaXYZ** [comment]
Ahhh, okay, that makes sense 👍

**Comment by DrakiaXYZ** [comment]
Just tested a system application (System Settings JPN to be specific), as well as a full comparison of encTitleKeys.bin vs decTitleKeys.bin encrypted using the above PHP, and it all seems to match up:

E:\Projects\3ds\boot9>php key.php 

 TitleId: 0004001000020000 

 Decrypted Key: 30f06ec42fa469aaXXXXXXXXXXXXXXXX 

 Encrypted Key: 91d040a371be6aXXXXXXXXXXXXXXXXXX 

 Expected EncKey: 91d040a371be6aXXXXXXXXXXXXXXXXXX

**Comment by TomEke** [comment]
Are you comparing on real 3ds? My implementation was previously wrong as no one uses the System Application keys.

**Comment by DrakiaXYZ** [comment]
Ohhh, no, I was comparing against the current list of encrypted system titlekeys on the site.

**Comment by nl255** [comment]
I believe removing the decrypted 3ds title keys will break certain programs such as 3dsestuff which is useful to have a pc side backup (ciangel is slow when creating cia files).

**Comment by DrakiaXYZ** [comment]
Shouldn't everything be creating CIAs with the encrypted key in the ticket anyways?

**Comment by TomEke** [comment]
I will not remove the code yet but will in the future. I will probably remove the decrypted title keys from the main page first.
