### ISSUE TITLE
Game Missing

### ISSUE THREAD

**Issue by Anonymous42456** [TomEke/WiiU-Title-Key#24]
Mario Sports Mix is missing.

**Comment by DrakiaXYZ** [comment]
Title keys are contributed by the community. No key = no game.

**Comment by Anonymous42456** [comment]
The game was on the website a few days ago...

**Comment by DrakiaXYZ** [comment]
That's useful information that should have been in your initial bug report.

**Comment by Anonymous42456** [comment]
Oops. Sorry. What to do?

**Comment by DrakiaXYZ** [comment]
At this point, wait for @TomEke to reply, he's the one who's going to have info on if/why it was removed.

**Comment by TomEke** [comment]
I did not remove any games. Are you sure it was on the website previously?

**Comment by Anonymous42456** [comment]
Ye cuz last week I downloaded it on Funkii U but then I deleted it because I wanted to redownload it from Wii U USB Helper.
