### ISSUE TITLE
Can't upload tickets

### ISSUE THREAD

**Issue by suzsuzuki** [TomEke/WiiU-Title-Key#26]
Tried to upload tickets and appears "Whoops, looks like something went wrong."

I'm pretty sure the ticket is legit

**Comment by TomEke** [comment]
Hello, there was a problem with my server files.

I have reprocessed all the uploaded tickets. Please check if the ticket is uploaded, and if not try again.

**Comment by suzsuzuki** [comment]
Great now works fine. Many thanks!
