### ISSUE TITLE
Fakesigned title shown as legit

### ISSUE THREAD

**Issue by ghost** [TomEke/WiiU-Title-Key#27]
Hello,
Title n°0005000010109800 (The Legend of Zelda: A Link to the Past USA) has its ticket downloadable from the website. Considering that it's a virtual console game, it should only have its titlekey available.

**Comment by TomEke** [comment]
Do not know how that got in there. I've removed the ticket.

**Comment by ghost** [comment]
Thanks for the prompt response.
I've just been informed that title n°0005000010199700 (Paper Mario USA) has the same problem.
