### ISSUE TITLE
Some UI/info suggestions

### ISSUE THREAD

**Issue by llakssz** [TomEke/WiiU-Title-Key#3]
Hi, thanks as always for the site :)

For the Wii U page, can you show whether something is dlc, updates, gameapp, etc?
It's just the as as 3ds, apart from in the title id: '008c' for 3ds dlc is simply '000c' for wii u.

How about displaying the size of the game? (Just add all the data sizes from the tmd)
Although dlc and updates (and rarely the base game itself) can get updated so the size won't always be correct...

You are actually checking if each ticket is legit, verifying the signatures? That's cool if so.
It's an neat way to also verify that the title key is correct.

Is it simple to upload tickets/keys to the site, from the wii u/3ds? Nothing preventing access or submissions when not using the web page directly?

And check this title id, you have it twice, once lower case and once uppercase:
0005000010145C00

Thanks!

**Comment by TomEke** [comment]
This is open source and I will accept pull requests. I forked this from the 3ds page when I originally moved to titlekeys.com so in time I will port back the features from the 3ds page.

>You are actually checking if each ticket is legit, verifying the signatures? 

Yes, this was suggested as a way to allow encrypted title keys to be uploaded into the 3DS page at some point. I will push the latest code soon.

>Is it simple to upload tickets/keys to the site, from the wii u/3ds? 

Yes. Myself used curl to batch upload the tickets and titlekeys originally.

**Comment by llakssz** [comment]
That is all good to hear, thank you :hot_pepper:

**Comment by TomEke** [comment]
Feel free to separate your requests on changes to the website out as separate issues.

**Comment by llakssz** [comment]
Well in a way, if some things are already implemented on the 3ds side, it might be easier/fast to back port it like you say, rather than recreate them.

But sure, for new features I understand, thanks.
