### ISSUE TITLE
Unintended Consequence

### ISSUE THREAD

**Issue by TJF588** [TomEke/WiiU-Title-Key#31]
Given the little information posted about this site, I uploaded my keys.txt thinking it would identify which were what, but instead I infer that I have uploaded all my personal tickets to this public database?! Is there any means by which I can have this submission undone?

**Comment by TomEke** [comment]
Hello, I do not share personal tickets on the web page. The only public tickets are the shared tickets from discs.

**Comment by TJF588** [comment]
Ah, I see. Thank you for the clarification.
