### ISSUE TITLE
How long does it take to add titles to the database?

### ISSUE THREAD

**Issue by ealgase** [TomEke/WiiU-Title-Key#35]
I just uploaded a keys.txt which contained keys for Animal Crossing Plaza (USA) and I'm wondering how long it will take to get added.

**Comment by shiftinv** [comment]
The website already has the titlekey for Animal Crossing Plaza; even though the region says JPN, the titlekey+ticket in this case are for Japan, NA and Europe. The reason for that is an issue with the .idbe reader of the website, specifically this part: [app/Title.php#L128-L131](https://github.com/TomEke/WiiU-Title-Key/blob/a4efc01d92f7b1f4c37bb7bf4470a42fa7bf914d/app/Title.php#L128-L131).
Right now the website is just missing the Animal Crossing Plaza ticket, the titlekey is already there.

**Comment by ealgase** [comment]
Weird.  Is the ticket even possible, since it was only released digitally?
