### ISSUE TITLE
title.tik downloads are incorrect Content-Type

### ISSUE THREAD

**Issue by PokeAcer549** [TomEke/WiiU-Title-Key#7]
Content-Type of the TIKs are `text/html` - surely they should be `text/plain` or similar?

**Comment by TomEke** [comment]
I had left it with the Laravel default. It can be changed, but does anything require it to be plain? The files are neither text nor plain.

**Comment by TomEke** [comment]
I added a content type: ```application/octet-stream``` which I believe fits better

**Comment by PokeAcer549** [comment]
That works better, thanks! 
(Sorry for being pedantic :P)
