### ISSUE TITLE
Is there anything like enctitlekeys.bin on the 3ds site

### ISSUE THREAD

**Issue by Jimmy-Z** [TomEke/WiiU-Title-Key#8]
So we don't have to parse HTML tables.

**Comment by Jimmy-Z** [comment]
I've found there is a json, still wondering if there is a binary form?

**Comment by TomEke** [comment]
I have not added one because as far as I know no program generates or uses one in so what sort of format would it be in?

**Comment by Jimmy-Z** [comment]
I'm fine with json, I'm just asking in case if it's already there. nice work by the way :)
