### ISSUE TITLE
[Suggestion] Parse keys.txt from Tik2SD

### ISSUE THREAD

**Issue by kidasquid** [TomEke/WiiU-Title-Key#9]
It would work like the decTitleKey uploader

**Comment by TomEke** [comment]
Can you share a sample of what the file?

I do not have a WiiU yet.

**Comment by kidasquid** [comment]
Found N unique tickets
0005000010100000 1234567890abcdef1234567890abcdef (0000/00000000.tik@0x0)
0005000010100001 2234567890abcdef1234567890abcdef (0000/00000001.tik@0x0)
0005000010100002 3234567890abcdef1234567890abcdef (0000/00000002.tik@0x0)

\n (LF) character at the end of each line. so we just need to parse every line from index 1 to the end

**Comment by kidasquid** [comment]
[keys.txt](https://github.com/TomEke/WiiU-Title-Key/files/708852/keys.txt)

**Comment by TomEke** [comment]
I've added some parsing for keys.txt and have tested it against a few keys.txt that have been uploaded.

**Comment by kidasquid** [comment]
Awesome!

**Comment by nl255** [comment]
I tried to upload my keys.txt from tik2sd and it just says "Whoops, looks like something went wrong".
